### ISSUE TITLE
Android installation instructions?

### ISSUE THREAD

**Issue by remib** [thisisbd/cordova-plugin-vuforia#19]
Are there any instructions to use the plugin with Android or is this still in development?

**Comment by dsgriffin** [comment]
@remib Hey, Android installation is the part upto where the iOS steps begin; just add the plugin, then the android platform, the Javascript and run it on your Android device. For an example see: https://github.com/dsgriffin/cordova-vuforia-example

**Comment by remib** [comment]
Thanks, all working.

It might be worth just adding a section to the readme explaining that there are no additional steps for Android to avoid any confusion!

**Comment by dsgriffin** [comment]
Glad to hear, and sure, we'll look into making the readme a little clearer r.e. Android usage
