### ISSUE TITLE
Support for Cloud database

### ISSUE THREAD

**Issue by remib** [thisisbd/cordova-plugin-vuforia#20]
Sorry to open another issue.

Correct me if I'm wrong, but with this plugin would I need to submit an App Update to a live app in the App Stores to add new targets? Is it possible to use a cloud database to manage targets?

**Comment by mattrayner** [comment]
Hi Remi,
 At the moment there's no support for the Vuforia cloud database service. This plugin was created for a brochure recognition system that detected certain pre-defined pages.

At the moment if you want to change targets it would require an update on the app store.

At the moment this is out of scope for the current plugin. If you wanted to get around this, you could either create a pull request, or, write some code to check your own server to see if new targets are available and if they are, download them to your device. Once on the device you should them be able to change your call to start Vuforia passing in the new data and XML files.

**Comment by remib** [comment]
No problem, I just thought I'd ask before moving forward. Thanks,

**Comment by mattrayner** [comment]
You're welcome 😃
