### ISSUE TITLE
Why use GPL license ?

### ISSUE THREAD

**Issue by nleclerc** [thisisbd/cordova-plugin-vuforia#8]
Hi,

i'd be interested to use thisplugin (and therefore contribute to it) but i can't since it's GPLed and my project is closed source.
What's the rationale for the license choice ?

**Comment by mattrayner** [comment]
Hi Nicolas,
 Initially we were being very cautious about the license - we were concerned that as the plugin contains Vuforia along with some snippets of sample code that a permissive license may have been on breach. We've checked more thoroughly now and to the best of our ability can't see any issues with making the project the more permissive MIT license.

We'll look at updating all the respective documentation now and close the issue when finished.

**Comment by nleclerc** [comment]
Wow !
Didn't expect you to react so quickly !
Thanks mate :-D

**Comment by mattrayner** [comment]
You're welcome! Have fun with it and if you have any issues, jump back omn here and we'll try to help :D

**Comment by mattrayner** [comment]
@nleclerc FYI we've successfully REVd the version number and the new plugin is on NPM

I though it happened earlier but travis cried...

**Comment by nleclerc** [comment]
Cool !
Thanks a lot.
